### PR TITLE
Do not show a bazilion stars as the submitted CC number

### PR DESCRIPTION
**Pull request by xurizaemon**
CiviCRM obfuscates the CC by hiding all but the last four numbers.

When the whole CC field has been encrypted and is a big blob of garbage, this looks ridiculous.

I didn't see a way to get CiviCRM hooks to modify variables for Smarty on these forms, so I just modified the templates. This is a bit shit since it creates problems for people who are customising those templates already, so a hook would be better ...

Should `hook_buildForm` or `hook_alterContent` have let me do this? Neither seemed to - I had access to the variables but changing them didn't modify the page output. Was also concerned that using buildform might prevent the values getting submitted eg on confirm page.

### CODE REVIEW

**Comment by xurizaemon** [comment]
Also, for templates, the same but SQL.

    UPDATE civicrm_msg_template 
    SET msg_text = replace(msg_text, '{$credit_card_number}', '{if $credit_card_number|count_characters > 19}XXXX-XXXX-XXXX-XXXX{else}{$credit_card_number}{/if}'), 
        msg_html = replace(msg_html, '{$credit_card_number}', '{if $credit_card_number|count_characters > 19}XXXX-XXXX-XXXX-XXXX{else}{$credit_card_number}{/if}');

Again would be better if we can intercept variables going to Smarty, but ... ¯\_(ツ)_/¯

**Comment by xurizaemon** [comment]
@eileenmcnaughton pls let me know if I should be submitting these to your CSE branch or somewhere else? re this PR and #12 also, both small fixes

**Comment by xurizaemon** [comment]
PS. I suspect this should be doable in buildForm but when I tried it didn't work.

Likely just personal issues with HTML QuickForm :scream:

**Comment by eileenmcnaughton** [comment]
I took a brief look at this - but we can't be doing tpl overrides in a payment processor - it's ok for single site use but can't be a generic solution.

Will try to find some time to look further - this is not specific to this processor as an issue.

**Pull request closed without merging**
