### PR TITLE
Issue #42. Use Webform CiviCRM + eWay together.

### PR DESCRIPTION
**Pull request by xurizaemon**
@eileenmcnaughton you might like this one too, goes into either clientside-encryption2 or master i expect

### CODE REVIEW

**Comment by eileenmcnaughton** [comment]
Didn't I ditch that dedupe check altogether in my branch?

**Comment by xurizaemon** [comment]
[checkDupe()](https://github.com/eileenmcnaughton/CiviCRM-eWay-recurring-payment-processor/blob/client-side-encryption-2/CRM/Core/Payment/Ewayrecurring.php#L205) apparently not

**Comment by eileenmcnaughton** [comment]
Just looked at this - yes - your comment is correct - webform needs to set invoiceID

**Comment by xurizaemon** [comment]
Took another look at this today - ContributionRecur API seems to use invoice_id as well as webform_civicrm?

* [api/v3/examples/ContributionRecur/Create.php](https://github.com/civicrm/civicrm-core/blob/master/api/v3/examples/ContributionRecur/Create.php#L39)
* [wf_crm_webform_postprocess::contributionRecur()](https://github.com/colemanw/webform_civicrm/blob/34b8ab1de01fa611a0311192ae58e4f5df4fdce4/includes/wf_crm_webform_postprocess.inc#L1735)

Might be that 438f48367f67e65bbf0f5770de7fe04df52e0fdb was similar, IDK - that one seems to have been where the extension expects to receive `$params['contributionRecurID']`, but if not present goes and gets `contribution.contribution_recur_id`?

**Comment by xurizaemon** [comment]
I now realise this related to work that is no longer ... So it's fine with us if you just close this 😆

FZ-9311

**Comment by eileenmcnaughton** [comment]
OK - I will close it out - things an always be re-opened

**Pull request closed without merging**
